### PR TITLE
V1.1 release

### PR DESCRIPTION
**Pull request by mattheworiordan**
@paddybyers @SimonWoolf I think Ruby is ready for a 1.1 release, so running this through CI.

Some PRs I would like to incorporate:

* [Transient publishing](https://github.com/ably/ably-ruby/pull/166)
* [Idempotent publishing](https://github.com/ably/ably-ruby/pull/165).  I believe that whilst support for the full spec is not yet fully rolled out in production, it's safe to merge this.

I will rebase those PRs on this branch now.

### CODE REVIEW

**Comment by paddybyers** [comment]
According to https://github.com/ably/docs/pull/473/files#diff-11900b395df266bc2bbfc1d11bdfc7a0R1232, the behaviour of idempotent publishing also needs to change with the switch to 1.1.

**Comment by SimonWoolf** [comment]
@mattheworiordan would be nice to confirm my analysis in https://github.com/ably/ably-ruby/issues/163#issuecomment-407015794 is right (if so you don't need to make any further changes for 1.1 re presence)

**Comment by mattheworiordan** [comment]
>  would be nice to confirm my analysis in #163 (comment) is right (if so you don't need to make any further changes for 1.1 re presence)

Ok, will prioritise

**Comment by mattheworiordan** [comment]
>  the behaviour of idempotent publishing also needs to change with the switch to 1.1.

@paddybyers OH. I implemented 1.2 in the Ruby lib :(  

That in theory is a bit of a blocker no?  Thoughts?

**Comment by mattheworiordan** [comment]
@paddybyers @SimonWoolf I believe this PR is ready to be merged and released as 1.1, barring any minor fixes in broken tests (such as idempotent tests which won't pass). See the "Ably Realtime Unified Spec 1.1" now, up to 88% coverage now.

screenshot 2018-11-28 at 00 45 46

**Pull request merged**
