### PR TITLE
Add RSL8, RSL8a lifecycle channel status

### LINKED ISSUE #362: Add support to get channel lifecycle status
Add support to get channel lifecycle status 

Channel lifecycle status is described at [Channel status / REST / [Docs]|[https://ably.com/docs/rest/channel-status#metadata-rest](https://ably.com/docs/rest/channel-status#metadata-rest)]

It is currently possible to retrieve channel lifecycle status in ably-go by using REST.Request and marshalling the result into a slice of empty interface.

**Example:**

```go
result, _ := restClient.Request("get", "/channels/test").Pages(context.Background())

result.Next(ctx)

var items []interface{}
if err := result.Items(&items); err != nil {
	fmt.Println(err)
}

fmt.Printf("%+v\n", items)
// [map[channelId:test name:test status:map[isActive:true occupancy:map[metrics:map[connections:1 presenceConnections:1 presenceMembers:1 presenceSubscribers:1 publishers:1 subscribers:1]]]]]
```

**Out of Scope**
Realtime subscription to Channel Lifecycle Events. This ticket is only for supporting REST client ‘Get’.

Please see this PR for more information [https://github.com/ably/docs/pull/1415](https://github.com/ably/docs/pull/1415|smart-link)

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-1856) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lukaszsliwa**
Resolves #362 

RSL8, RSL8a

### CODE REVIEW

**Review by owenpearson — CHANGES_REQUESTED** [review]
It looks like `Channel.status` doesn't actually make the request to the REST API here, there should be a call to `client.get`, see the [example from ably-go](https://github.com/ably/ably-go/blob/main/ably/rest_channel.go#L184-L197). Also we need an integration test for this, see the [ably-js test](https://github.com/ably/ably-js/blob/main/test/rest/status.test.js#L23-L41) for an example.

**Review by owenpearson — APPROVED** [review]
@lukaszsliwa That's so weird, not sure how I missed both of those when I reviewed this before 😅 anyway, LGTM now

**Review by owenpearson — CHANGES_REQUESTED** [review]
Actually, before we merge this would you mind adding some rubydoc comments to the new models? You can use the descriptions from https://github.com/ably/docs/blob/main/content/client-lib-development-guide/features.textile#channeldetails

**Comment by lukaszsliwa** [comment]
> Actually, before we merge this would you mind adding some rubydoc comments to the new models? You can use the descriptions from https://github.com/ably/docs/blob/main/content/client-lib-development-guide/features.textile#channeldetails

Okey, I will add some more comments

**Review by owenpearson — APPROVED** [review]
Nice work 👍

**Pull request merged**
