### PR TITLE
Add transport_params option to realtime client (RTC1f1)

### PR DESCRIPTION
**Pull request by TheSmartnik**
Resolve https://github.com/ably/ably-ruby/issues/176

### CODE REVIEW

**Comment by jamienewcomb** [comment]
@TheSmartnik this ready for review?

**Comment by TheSmartnik** [comment]
@jamienewcomb almost. Should be ready in a few hours.

**Comment by jamienewcomb** [comment]
Thank you, if you could assign Owen and Quintin once its ready

**Review by owenpearson — APPROVED** [review]
Nice work on this 🙂  i've added a commit to remove transport params from the 'known limitations' in our readme.

**Pull request merged**
