### PR TITLE
RSC15d test fixes; add (failing) tests for GET as well as POST

### PR DESCRIPTION
**Pull request by SimonWoolf**
Linked these from https://github.com/ably/ably-ruby/issues/126#issuecomment-382725426, but said I'd make a pr. Main issue with the previous tests is that they pass a `max_retry_duration` param, but that's just ignored as the lib expects it to be `http_max_retry_duration`, which is why the old second test was passing even though it expects the opposite of what should happen (it asserts that a fallback was tried even though it's passing options that should mean no fallbacks are tried).

The GET test I added is failing, probably due to https://bugs.ruby-lang.org/issues/10674 . No attempt at a fix here, just highlighting the issue.

### CODE REVIEW

**Comment by SimonWoolf** [comment]
> Do you think with dynamic languages we should perhaps warn people when they're passing in options that are not supported in Hashes/Dictionary/Object-like arguments?

Sure, why not, seems reasonable

**Comment by mattheworiordan** [comment]
2 tests are consistently failing in this PR...

**Comment by SimonWoolf** [comment]
> 2 tests are consistently failing in this PR...

Yes. See original comment.

>> The GET test I added is failing, probably due to https://bugs.ruby-lang.org/issues/10674 . No attempt at a fix here, just highlighting the issue.

**Comment by mattheworiordan** [comment]
@SimonWoolf @paddybyers @funkyboy you are going to love this one.  I thought whilst I am deep in Ruby code, I may as well just fix @SimonWoolf's PR as it had some failing tests.

After a little investigation, I noticed that the local web server was reporting two requests being received, when I was 100% sure that the client library was making only one request.  And then I discovered that Ruby retries what it believes are idempotent requests twice without providing any feedback...  See https://github.com/ably/ably-ruby/pull/148/commits/cb32020dceaa096cc31027f57e6e908afde0fb2e.

To be honest I am not 100% convinced we should introduce a whole new HTTP library to this Gem just to work around the problem, but it does seem like we have little choice unfortunately before Ruby 2.5 to fix this problem.

WDYT?

**Comment by mattheworiordan** [comment]
@SimonWoolf oops, I should read your comments 👍

**Pull request merged**
