### PR TITLE
Channel name encoding error for REST requests

### PR DESCRIPTION
**Pull request by mattheworiordan**
This PR is just [@smeyfroi's PR](https://github.com/ably/ably-ruby/pull/118) plus one additional test to prevent a regression.

### CODE REVIEW

**Comment by smeyfroi** [comment]
pr looks good but travis not happy... these look like the unrelated fails i was seeing on the old pr... need to leave these to you @mattheworiordan i reckon, sorry!

**Comment by mattheworiordan** [comment]
> pr looks good but travis not happy.

Good news is that those errors are unrelated and not an issue.  One is a test issue introduced by a hotfix https://github.com/ably/ably-ruby/commit/ee038c398fb91bd2fed55f1cafcc498bad178179.  The others are errors simply due to the fixtures not working as expected for push notifications and this test suite not supporting push (see https://github.com/ably/ably-ruby/pull/115).  So this branch is definitely save for you to use i.e. in your Gemfile `gem `ably`, git: 'https://github.com/ably/ably-ruby.git', branch: 'presence_error'`.

I will get this fixed along with the heartbeat issue soon and do a new release.

**Comment by smeyfroi** [comment]
ah great. i have the 'ably-rest' gem in my bundle here, which doesn't do much beyond bringing this repo in as a submodule. can i just use 'ably-ruby' in my bundle if i'm only using the rest api?

**Comment by mattheworiordan** [comment]
> can i just use 'ably-ruby' in my bundle if i'm only using the rest api?

Yup, you can, you just get a few extra dependencies but it won't make any difference in reality.  I'll try and get a release out next week.

**Comment by smeyfroi** [comment]
awesome, thanks matthew :-)

**Comment by mattheworiordan** [comment]
This is now merged and available in stable release v1.0.4

**Pull request merged**
