### PR TITLE
Add a spec for #RTN11c

### PR DESCRIPTION
**Pull request by TheSmartnik**
As a part of https://github.com/ably/ably-ruby/issues/244

### CODE REVIEW

**Comment by lukaszsliwa** [comment]
`DISCONNECTED` state confirmation is missing. `SUSPENDED` connection status works. I think it would be good to divide these tests in contexts base on the connection status.

```
(RTN11c) If the state is DISCONNECTED or SUSPENDED, skips the ongoing wait in the retry process described in RTN14d and RTN14e, so that the next reconnection attempt happens immediately.
```

**Comment by TheSmartnik** [comment]
@lukaszsliwa done

**Review by lukaszsliwa — APPROVED** [review]
Looks good to me. Thanks @TheSmartnik

**Review by owenpearson — APPROVED** [review]
LGTM, thanks

**Pull request merged**
